### ISSUE TITLE
Something wrong with "flashloan = FlashloanV2[len(FlashloanV2) - 1]".

### ISSUE THREAD

**Issue by tgoszc** [brownie-mix/aave-flashloan-mix#10]
`
brownie run scripts/run_flash_loan_v2.py --network kovan
`
>   File "./scripts/run_flash_loan_v2.py", line 18, in main
    print(FlashloanV2[-1])
  File "brownie/network/contract.py", line 158, in __getitem__
    return self._contracts[i]
IndexError: list index out of range

Here is some of the code:

```
def main(): 
    acct = accounts.add(config["wallets"]["from_key"])
    print("Getting Flashloan contract...")
    flashloan = FlashloanV2[len(FlashloanV2) - 1]
    weth = interface.WethInterface(config["networks"][network.show_active()]["weth"])<br class="Apple-interchange-newline">
```

So I print(len(FlashLoanV2)) and get 0. 
seems like it can't read FlashLoanV2 object as an array, so I can't get the address in it through FlashLoanV2[...].
How to solve this, it's because of my python version or something else?
Thanks!

**Comment by PatrickAlphaC** [comment]
You have to deploy the flash loan contract first. Did you run the deployment script first?

Closing for now, but feel free to follow up here.
