### ISSUE TITLE
Unable to publish and verify contract

### ISSUE THREAD

**Issue by chiku524** [brownie-mix/aave-flashloan-mix#9]
Adding _publish_source=True_ as an argument to the _deploy_ function inside _deployment_v2.py_ does still deploy the contract, but the contract is always unable to verify. I have tried publishing the contract through this method, as well as using the brownie console but it never seems to work for me.

![image](https://user-images.githubusercontent.com/61144399/120430905-b31b4280-c345-11eb-9f14-bf9b3a39faab.png)

Thanks for the repo, by the way. Very useful.

**Comment by PatrickAlphaC** [comment]
This is an issue with Brownie as a whole, can you actually make this an issue there? 

And instead of using screenshots, it's much easier to search for your issue if you copy paste the code, just be sure to use 3 back tics ``` at the start and end of your code.
